# must be unique in a given SonarQube Server instance
sonar.projectKey=vedarth-Angular-countryviewer

# --- optional properties ---

# defaults to project key
sonar.projectName=vedarth-Angular-countryviewer
 defaults to 'not provided'
sonar.projectVersion=1.0
sonar.host.url=http://192.168.0.32:9000
sonar.token=squ_e242e9c717eb60afafe402a8d9ffdaca65d8ad47
 
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts, **/.angular/**, **/.vscode/**, **/.git/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/country-view/lcov.info
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8